### ISSUE TITLE
Example with Symfony App?

### ISSUE THREAD

**Issue by Briones** [jtreminio/volsync#1]
First of all thanks for this initiative, I really want to try it, since is really annoying working with Docker in Mac with projects that manages several files.

I read your README file but it said:

> 
> In this scenario you are working on files in src or the root directory. You are not actively editing any files within app/cache or vendor but your IDE wants to see the contents and packages installed there so it can provide typehinting.
> 
> As contents within app/cache are machine-generated and you are not actively editing them, and as contents within vendor are not continuously changed it is safe to delay syncing from the container to the host.

And in the example you just use a container volume for `var/www` and two named volumes for cache and vendor:

``` volumes:
            - $PWD:/var/www
            - cache:/var/www/app/cache
            - vendor:/var/www/vendor
```

But what happen with the `src` folder? and the others like the `app` or `bin` folder in a Symfony project? 

Maybe could be something like this? Putting all the current directory into a container volume and just the `cache` and `vendor` folders into a named volume? Or it will be affect that those folders are also part of the current folder?

``` volumes:
            - $PWD:/app
            - cache:/var/cache
            - vendor:/vendor
```

Thanks in advance!

**Comment by jtreminio** [comment]
$PWD is assumed the root of your project. /src, /app, /vendor would all be at this level.

The named volumes overlap the bind mount. Your container doesn't see the contents of /vendor and /app/cache because those are replaced.
